import type { IntegrationDefinition } from "./types"

export const integrationRegistry = [
  {
    key: "open_banking",
    name: "Open Banking",
    category: "Finanzen",
    description: "PSD2 Bankverbindungen, Kontosynchronisation und Zahlungsabgleich vorbereiten.",
    iconKey: "landmark",
    marketplaceModuleKey: "open_banking",
    requiredFeatureFlag: "open_banking.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/open_banking",
    logsRoute: "/dashboard-v2/integrations/open_banking#logs"
  },
  {
    key: "datev",
    name: "DATEV",
    category: "Finanzen",
    description: "DATEV-Export, Buchungsdaten und Steuerberater-Uebergabe.",
    iconKey: "file-text",
    marketplaceModuleKey: "datev",
    requiredFeatureFlag: "datev.enabled",
    requiredPlan: "business",
    authType: "api_key",
    status: "installed",
    syncSupported: true,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/datev",
    logsRoute: "/dashboard-v2/integrations/datev#logs"
  },
  {
    key: "paypal",
    name: "PayPal",
    category: "Finanzen",
    description: "PayPal-Zahlungen, Zahlungsstatus und Webhook-Readiness vorbereiten.",
    iconKey: "credit-card",
    marketplaceModuleKey: "paypal",
    requiredFeatureFlag: "payments.paypal",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/paypal",
    logsRoute: "/dashboard-v2/integrations/paypal#logs"
  },
  {
    key: "stripe",
    name: "Stripe",
    category: "Finanzen",
    description: "Stripe Checkout, Zahlungsabgleich und Webhooks vorbereiten.",
    iconKey: "credit-card",
    marketplaceModuleKey: "stripe",
    requiredFeatureFlag: "payments.stripe",
    requiredPlan: "business",
    authType: "api_key",
    status: "available",
    syncSupported: true,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/stripe",
    logsRoute: "/dashboard-v2/integrations/stripe#logs"
  },
  {
    key: "shopify",
    name: "Shopify",
    category: "Commerce",
    description: "Bestellungen, Produkte und Kunden aus Shopify synchronisieren.",
    iconKey: "store",
    marketplaceModuleKey: "shopify",
    requiredFeatureFlag: "shopify.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/shopify",
    logsRoute: "/dashboard-v2/integrations/shopify#logs"
  },
  {
    key: "woocommerce",
    name: "WooCommerce",
    category: "Commerce",
    description: "WooCommerce-Bestellungen, Produkte und Rechnungen vorbereiten.",
    iconKey: "store",
    marketplaceModuleKey: "woocommerce",
    requiredFeatureFlag: "woocommerce.enabled",
    requiredPlan: "business",
    authType: "api_key",
    status: "available",
    syncSupported: true,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/woocommerce",
    logsRoute: "/dashboard-v2/integrations/woocommerce#logs"
  },
  {
    key: "amazon",
    name: "Amazon",
    category: "Commerce",
    description: "Amazon-Bestellungen und Marketplace-Abgleich vorbereiten.",
    iconKey: "package",
    marketplaceModuleKey: "amazon",
    requiredFeatureFlag: "amazon.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/amazon",
    logsRoute: "/dashboard-v2/integrations/amazon#logs"
  },
  {
    key: "ebay",
    name: "eBay",
    category: "Commerce",
    description: "eBay-Verkaeufe und Bestelldaten als Mock-Integration vorbereiten.",
    iconKey: "shopping-cart",
    marketplaceModuleKey: "ebay",
    requiredFeatureFlag: "ebay.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/ebay",
    logsRoute: "/dashboard-v2/integrations/ebay#logs"
  },
  {
    key: "nextcloud",
    name: "Nextcloud",
    category: "Cloud",
    description: "Dokumente und Exporte mit Nextcloud verbinden.",
    iconKey: "cloud",
    marketplaceModuleKey: "nextcloud",
    requiredFeatureFlag: "nextcloud.enabled",
    requiredPlan: "business",
    authType: "basic",
    status: "available",
    syncSupported: true,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/nextcloud",
    logsRoute: "/dashboard-v2/integrations/nextcloud#logs"
  },
  {
    key: "paperless_ngx",
    name: "Paperless-ngx",
    category: "Cloud",
    description: "Dokumentenarchiv, Tags und Belegablage vorbereiten.",
    iconKey: "archive",
    marketplaceModuleKey: "paperless_ngx",
    requiredFeatureFlag: "paperless_ngx.enabled",
    requiredPlan: "business",
    authType: "token",
    status: "available",
    syncSupported: true,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/paperless_ngx",
    logsRoute: "/dashboard-v2/integrations/paperless_ngx#logs"
  },
  {
    key: "google_drive",
    name: "Google Drive",
    category: "Cloud",
    description: "Dokumente und Exportdateien mit Google Drive synchronisieren.",
    iconKey: "cloud",
    marketplaceModuleKey: "google_drive",
    requiredFeatureFlag: "google_drive.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/google_drive",
    logsRoute: "/dashboard-v2/integrations/google_drive#logs"
  },
  {
    key: "onedrive",
    name: "OneDrive",
    category: "Cloud",
    description: "OneDrive-Dokumentablage und Export-Readiness vorbereiten.",
    iconKey: "cloud",
    marketplaceModuleKey: "onedrive",
    requiredFeatureFlag: "onedrive.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: true,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/onedrive",
    logsRoute: "/dashboard-v2/integrations/onedrive#logs"
  },
  {
    key: "smtp",
    name: "SMTP",
    category: "Kommunikation",
    description: "E-Mail-Versand ueber SMTP als Konfigurationsgrundlage vorbereiten.",
    iconKey: "mail",
    marketplaceModuleKey: "smtp",
    requiredFeatureFlag: "smtp.enabled",
    requiredPlan: "free",
    authType: "basic",
    status: "available",
    syncSupported: false,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/smtp",
    logsRoute: "/dashboard-v2/integrations/smtp#logs"
  },
  {
    key: "whatsapp",
    name: "WhatsApp",
    category: "Kommunikation",
    description: "Kundenkommunikation und Benachrichtigungen per WhatsApp vorbereiten.",
    iconKey: "message-circle",
    marketplaceModuleKey: "whatsapp",
    requiredFeatureFlag: "whatsapp.enabled",
    requiredPlan: "business",
    authType: "token",
    status: "available",
    syncSupported: false,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/whatsapp",
    logsRoute: "/dashboard-v2/integrations/whatsapp#logs"
  },
  {
    key: "slack",
    name: "Slack",
    category: "Kommunikation",
    description: "Slack-Benachrichtigungen und Workflow-Updates vorbereiten.",
    iconKey: "message-square",
    marketplaceModuleKey: "slack",
    requiredFeatureFlag: "slack.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: false,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/slack",
    logsRoute: "/dashboard-v2/integrations/slack#logs"
  },
  {
    key: "microsoft_teams",
    name: "Microsoft Teams",
    category: "Kommunikation",
    description: "Teams-Freigaben, Benachrichtigungen und Statusupdates vorbereiten.",
    iconKey: "messages-square",
    marketplaceModuleKey: "microsoft_teams",
    requiredFeatureFlag: "microsoft_teams.enabled",
    requiredPlan: "business",
    authType: "oauth",
    status: "available",
    syncSupported: false,
    webhookSupported: true,
    settingsRoute: "/dashboard-v2/integrations/microsoft_teams",
    logsRoute: "/dashboard-v2/integrations/microsoft_teams#logs"
  },
  {
    key: "openai",
    name: "OpenAI",
    category: "KI",
    description: "KI-Assistent, Textanalyse und Automationen vorbereiten.",
    iconKey: "brain",
    marketplaceModuleKey: "openai",
    requiredFeatureFlag: "ai.enabled",
    requiredPlan: "business",
    authType: "api_key",
    status: "available",
    syncSupported: false,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/openai",
    logsRoute: "/dashboard-v2/integrations/openai#logs"
  },
  {
    key: "claude",
    name: "Claude",
    category: "KI",
    description: "Claude-Modellprovider als KI-Adapter vorbereiten.",
    iconKey: "brain",
    marketplaceModuleKey: "claude",
    requiredFeatureFlag: "claude.enabled",
    requiredPlan: "business",
    authType: "api_key",
    status: "available",
    syncSupported: false,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/claude",
    logsRoute: "/dashboard-v2/integrations/claude#logs"
  },
  {
    key: "gemini",
    name: "Gemini",
    category: "KI",
    description: "Gemini-Modellprovider als KI-Adapter vorbereiten.",
    iconKey: "brain",
    marketplaceModuleKey: "gemini",
    requiredFeatureFlag: "gemini.enabled",
    requiredPlan: "business",
    authType: "api_key",
    status: "available",
    syncSupported: false,
    webhookSupported: false,
    settingsRoute: "/dashboard-v2/integrations/gemini",
    logsRoute: "/dashboard-v2/integrations/gemini#logs"
  }
] as const satisfies readonly IntegrationDefinition[]

export type IntegrationKey = (typeof integrationRegistry)[number]["key"]
