services:
  web-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ${DREAM_INVOICE_IMAGE:-ghcr.io/dream-de/invoice-app:latest}

  server-worker:
    build:
      context: .
      dockerfile: docker/ServerWorker.Dockerfile
    image: ${DREAM_INVOICE_WORKER_IMAGE:-ghcr.io/dream-de/invoice-app-worker:latest}
