export type ModulePlan = "free" | "business" | "enterprise"
export type ModuleStatus = "active" | "locked" | "beta" | "installed" | "available"
export type ModuleCategory = "core" | "business" | "enterprise" | "marketplace"

export type AppModule = {
  key: string
  name: string
  description: string
  category: ModuleCategory
  iconKey: string
  route: string
  requiredPlan: ModulePlan
  marketplace: boolean
  featureFlag?: string
  installedByDefault: boolean
  visibleInSidebar: boolean
  visibleInDashboard: boolean
  visibleInSearch: boolean
  status: ModuleStatus
  dependencies?: string[]
  requiredPermission?: string
}

export const appRegistry = [
  {
    key: "dashboard",
    name: "Dashboard",
    description: "Zentrale Uebersicht fuer Kennzahlen, Aufgaben und Workflows.",
    category: "core",
    iconKey: "bar-chart-3",
    route: "/dashboard-v2",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "customers",
    name: "Kunden",
    description: "Kundenstammdaten, Kontakte und Adressen verwalten.",
    category: "core",
    iconKey: "users",
    route: "/dashboard-v2/customers",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "offers",
    name: "Angebote",
    description: "Angebote erstellen, versenden und in Rechnungen ueberfuehren.",
    category: "core",
    iconKey: "file-text",
    route: "/dashboard-v2/offers",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "invoices",
    name: "Rechnungen",
    description: "Rechnungen, Zahlstatus und Belege zentral steuern.",
    category: "core",
    iconKey: "receipt",
    route: "/dashboard-v2/invoices",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "documents",
    name: "Dokumente",
    description: "Dokumente, Vorlagen und Dateien verwalten.",
    category: "core",
    iconKey: "folder-open",
    route: "/dashboard-v2/documents",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "email",
    name: "E-Mail",
    description: "E-Mail-Versand und Kommunikationsvorlagen vorbereiten.",
    category: "core",
    iconKey: "mail",
    route: "/dashboard-v2/settings/email",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "reports",
    name: "Berichte",
    description: "Auswertungen, Reports und Exportansichten.",
    category: "core",
    iconKey: "bar-chart-3",
    route: "/dashboard-v2/reports",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "finance",
    name: "Finanzen",
    description: "Manuelle Finanzen, Zahlungen und Kontoueberblick.",
    category: "core",
    iconKey: "wallet-cards",
    route: "/dashboard-v2/finance",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "settings",
    name: "Einstellungen",
    description: "Mandant, System, Benutzer und Konfiguration.",
    category: "core",
    iconKey: "settings",
    route: "/dashboard-v2/settings",
    requiredPlan: "free",
    marketplace: false,
    installedByDefault: true,
    visibleInSidebar: true,
    visibleInDashboard: false,
    visibleInSearch: true,
    status: "active",
    requiredPermission: "settings.read"
  },
  {
    key: "projects",
    name: "Projekte",
    description: "Projektplanung, Budgets und Projektstatus.",
    category: "business",
    iconKey: "building-2",
    route: "/dashboard-v2/projects",
    requiredPlan: "business",
    marketplace: false,
    featureFlag: "projects.enabled",
    installedByDefault: false,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "time_tracking",
    name: "Zeiterfassung",
    description: "Arbeitszeiten, Timer und Projektzeiten erfassen.",
    category: "business",
    iconKey: "clock",
    route: "/dashboard-v2/time-tracking",
    requiredPlan: "business",
    marketplace: false,
    featureFlag: "time_tracking.enabled",
    installedByDefault: false,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "rest_api",
    name: "REST API",
    description: "API-Zugriff fuer externe Systeme vorbereiten.",
    category: "business",
    iconKey: "code-2",
    route: "/dashboard-v2/api",
    requiredPlan: "business",
    marketplace: false,
    featureFlag: "api.enabled",
    installedByDefault: false,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    requiredPermission: "api.read"
  },
  {
    key: "webhooks",
    name: "Webhooks",
    description: "Webhook-Endpunkte und Events verwalten.",
    category: "business",
    iconKey: "webhook",
    route: "/dashboard-v2/api",
    requiredPlan: "business",
    marketplace: false,
    featureFlag: "webhooks.enabled",
    installedByDefault: false,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    dependencies: ["rest_api"],
    requiredPermission: "api.read"
  },
  {
    key: "open_banking_basic",
    name: "Open Banking Basis",
    description: "Basisfunktionen fuer PSD2 und Bankverbindungen vorbereiten.",
    category: "business",
    iconKey: "landmark",
    route: "/dashboard-v2/finance",
    requiredPlan: "business",
    marketplace: false,
    featureFlag: "open_banking.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active"
  },
  {
    key: "payment_matching",
    name: "Zahlungsabgleich",
    description: "Zahlungen Rechnungen zuordnen und Status vorbereiten.",
    category: "business",
    iconKey: "receipt",
    route: "/dashboard-v2/finance",
    requiredPlan: "business",
    marketplace: false,
    featureFlag: "open_banking.payment_matching",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    dependencies: ["open_banking_basic"]
  },
  {
    key: "multi_company",
    name: "Multi-Unternehmen",
    description: "Mehrere Unternehmen und Workspaces zentral steuern.",
    category: "enterprise",
    iconKey: "building-2",
    route: "/dashboard-v2/companies",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "multi_company.enabled",
    installedByDefault: false,
    visibleInSidebar: true,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    requiredPermission: "companies.read"
  },
  {
    key: "sso",
    name: "SSO",
    description: "Single Sign-on fuer Enterprise-Umgebungen vorbereiten.",
    category: "enterprise",
    iconKey: "shield-check",
    route: "/dashboard-v2/users",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "sso.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    requiredPermission: "users.read"
  },
  {
    key: "white_label",
    name: "White Label",
    description: "Branding und Mandantenauftritt anpassen.",
    category: "enterprise",
    iconKey: "sparkles",
    route: "/dashboard-v2/settings",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "white_label.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    requiredPermission: "settings.read"
  },
  {
    key: "cashflow",
    name: "Cashflow",
    description: "Liquiditaet und Zahlungsstroeme auswerten.",
    category: "enterprise",
    iconKey: "bar-chart-3",
    route: "/dashboard-v2/finance",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "open_banking.cashflow_forecast",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    dependencies: ["open_banking_basic"]
  },
  {
    key: "forecast",
    name: "Forecast",
    description: "Finanzielle Vorschau und Szenarien vorbereiten.",
    category: "enterprise",
    iconKey: "trending-up",
    route: "/dashboard-v2/reports",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "open_banking.cashflow_forecast",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    dependencies: ["cashflow"]
  },
  {
    key: "bank_rules",
    name: "Bankregeln",
    description: "Automatische Regeln fuer Banktransaktionen vorbereiten.",
    category: "enterprise",
    iconKey: "landmark",
    route: "/dashboard-v2/finance",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "open_banking.bank_rules",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    dependencies: ["open_banking_basic"]
  },
  {
    key: "multi_banking",
    name: "Multi-Banking",
    description: "Mehrere Bankverbindungen und Synchronisation vorbereiten.",
    category: "enterprise",
    iconKey: "landmark",
    route: "/dashboard-v2/finance",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "open_banking.bank_sync",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    dependencies: ["open_banking_basic"]
  },
  {
    key: "advanced_audit_logs",
    name: "Erweiterte Audit Logs",
    description: "Erweiterte Protokolle fuer Compliance und Revision.",
    category: "enterprise",
    iconKey: "shield-check",
    route: "/dashboard-v2/logs",
    requiredPlan: "enterprise",
    marketplace: false,
    featureFlag: "advanced_audit_logs.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "active",
    requiredPermission: "audit.read"
  },
  {
    key: "open_banking",
    name: "Open Banking",
    description: "PSD2 Bankverbindungen, Bank-Sync und Zahlungsabgleich.",
    category: "marketplace",
    iconKey: "landmark",
    route: "/dashboard-v2/finance",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "open_banking.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available",
    dependencies: ["open_banking_basic"]
  },
  {
    key: "datev",
    name: "DATEV",
    description: "DATEV-Export und Steuerberater-Uebergabe vorbereiten.",
    category: "marketplace",
    iconKey: "file-text",
    route: "/dashboard-v2/finance",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "datev.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "ocr",
    name: "OCR",
    description: "Belegerkennung und Dokumenten-OCR vorbereiten.",
    category: "marketplace",
    iconKey: "scan-line",
    route: "/dashboard-v2/documents",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "ocr.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "warehouse",
    name: "Lager",
    description: "Lagerorte, Bestaende und Warenbewegungen.",
    category: "marketplace",
    iconKey: "package",
    route: "/dashboard-v2/articles",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "warehouse.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "shopify",
    name: "Shopify",
    description: "Shopify-Bestellungen, Produkte und Kunden synchronisieren.",
    category: "marketplace",
    iconKey: "store",
    route: "/dashboard-v2/integrations",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "shopify.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "woocommerce",
    name: "WooCommerce",
    description: "WooCommerce-Bestellungen, Produkte und Rechnungen vorbereiten.",
    category: "marketplace",
    iconKey: "store",
    route: "/dashboard-v2/integrations",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "woocommerce.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "nextcloud",
    name: "Nextcloud",
    description: "Dateien und Dokumente mit Nextcloud verbinden.",
    category: "marketplace",
    iconKey: "cloud",
    route: "/dashboard-v2/settings/portal",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "nextcloud.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "paperless_ngx",
    name: "Paperless-ngx",
    description: "Dokumentenarchiv, Tags und Belegablage vorbereiten.",
    category: "marketplace",
    iconKey: "archive",
    route: "/dashboard-v2/settings/portal",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "paperless_ngx.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "google_drive",
    name: "Google Drive",
    description: "Dokumente und Exporte mit Google Drive verbinden.",
    category: "marketplace",
    iconKey: "cloud",
    route: "/dashboard-v2/settings/portal",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "google_drive.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "openai",
    name: "OpenAI",
    description: "KI-Assistent, Textanalyse und Automationen vorbereiten.",
    category: "marketplace",
    iconKey: "brain",
    route: "/dashboard-v2/ai-assistant",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "ai.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "beta"
  },
  {
    key: "whatsapp",
    name: "WhatsApp",
    description: "Kundenkommunikation per WhatsApp vorbereiten.",
    category: "marketplace",
    iconKey: "message-circle",
    route: "/dashboard-v2/integrations",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "whatsapp.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "slack",
    name: "Slack",
    description: "Benachrichtigungen und Workflows mit Slack verbinden.",
    category: "marketplace",
    iconKey: "message-square",
    route: "/dashboard-v2/integrations",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "slack.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  },
  {
    key: "microsoft_teams",
    name: "Microsoft Teams",
    description: "Benachrichtigungen und Freigaben mit Teams verbinden.",
    category: "marketplace",
    iconKey: "messages-square",
    route: "/dashboard-v2/integrations",
    requiredPlan: "business",
    marketplace: true,
    featureFlag: "microsoft_teams.enabled",
    installedByDefault: false,
    visibleInSidebar: false,
    visibleInDashboard: true,
    visibleInSearch: true,
    status: "available"
  }
] as const satisfies readonly AppModule[]

export type AppModuleKey = (typeof appRegistry)[number]["key"]

export function getModuleByKey(key: string): AppModule | undefined {
  return appRegistry.find((module) => module.key === key)
}
